name: Android CI

on:
  push:
    branches:
      - main

jobs:
  Build-APK:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./AndroidTemplate_HelloGradle/gradlew

      - name: Build APK
        working-directory: AndroidTemplate_HelloGradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: AndroidTemplate_HelloGradle/app/build/outputs/apk/debug/app-debug.apk
